### ISSUE TITLE
Modo Nocturno

### ISSUE THREAD

**Issue by Jimena77777777777777** [hectorfd/TodoTareas#12]
Como: Usuario
Quiero: Modo Nocturno 
Para: Disminuir el cansancio visual al usar la aplicación en ambientes con poca luz y mejorar la experiencia de uso en la noche.

**Comment by hectorfd** [comment]
Criterios de aceptación:

El modo nocturno debe activarse automáticamente según la diferencia horaria del usuario.
El usuario debe poder activar o desactivar el modo nocturno manualmente desde el menú de configuración.
Los textos y los íconos deben ser visibles y legibles en el modo nocturno, con un contraste adecuado para evitar fatiga visual.
La interfaz debe conservar su funcionalidad completa en modo nocturno, sin afectar negativamente la experiencia de usuario.
